### ISSUE TITLE
Docker Failed to Load Tree Error

### ISSUE THREAD

**Issue by cinetube** [QingWei-Li/notea#124]
Here is my docker compose - 

```
services:
  notea-webapp:
    image: cinwell/notea
    container_name: notea-webapp
    ports:
      - "3000:3000"
    environment:
      - STORE_ACCESS_KEY=raspberry
      - STORE_SECRET_KEY=raspberry
      - STORE_BUCKET=notea
      - STORE_END_POINT=http://notea-db:9002
      - STORE_FORCE_PATH_STYLE=true
      - PASSWORD=raspberry
      - COOKIE_SECURE=false
      - BASE_URL="http://192.168.137.128:3000/"
  notea-db:
    image: minio/minio
    container_name: notea-db
    ports:
      - "9002:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=raspberry
      - MINIO_ROOT_PASSWORD=raspberry
    volumes:
      - /mnt/data:/data
    command: server /data --console-address ":9001"
```

I am facing problem to connect Notea with notea-db. Please help me to resolve this error. 

![Screenshot 2021-11-24 203425](https://user-images.githubusercontent.com/23441775/143257893-d186f5b2-5d3c-41d4-8ace-9369df821b96.jpg)
