### ISSUE TITLE
Unable login (unable to disable password using reverse proxy)

### ISSUE THREAD

**Issue by axeII** [QingWei-Li/notea#38]
Hi,

I would like to try this project however currently I am unable to login.  😔

My setup is to user minio instead of S3 + traefik as https proxy to login via https to notea.
Page loads normally asking for password however "test" password passed via variable doesn't work. Please see the error log.

I also tried to disable login page using variable `DISABLE_PASSORD`(which I would like to replace by sso), however notea still asks for password. I tried both http and https - there is not diference. 

However I was _able to login_ without password when I accessed to notea directly eg: http://172.34.0.34:3000  

My docker-compose:
```
version: "3.7"
services:
  notea:
    image: cinwell/notea
    container_name: notea
    environment:
      - STORE_ACCESS_KEY=minioadmin
      - STORE_SECRET_KEY=minioadmin
      - STORE_BUCKET=notea
      - STORE_END_POINT=http://minio:9000
      - STORE_FORCE_PATH_STYLE=true
      - PASSWORD="test"
      - COOKIE_SECURE=true
      - BASE_URL="https://notea.local.lan"
        #- DISABLE_PASSWORD=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.notea.rule=Host(`notea.local.lan`)
      - traefik.http.services.notea.loadbalancer.server.port=3000
      - traefik.http.routers.notea.entrypoints=web-secure
      - traefik.http.routers.notea.tls=true

  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - /data/notea:/data
    command: server /data
```

error log: 
```
notea-webapp | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
notea-webapp | info  - Using webpack 4. Reason: future.webpack5 option not enabled https://nextjs.org/docs/messages/webpack5
notea-webapp | {
notea-webapp |   name: 'API_ERR_NEED_LOGIN',
notea-webapp |   message: 'Please login first',
notea-webapp |   status: 401,
notea-webapp |   stack: 'API_ERR_NEED_LOGIN: Please login first\n' +
notea-webapp |     '    at APIError.throw (/app/.next/server/pages/index.js:2124:19)\n' +
notea-webapp |     '    at Array.<anonymous> (/app/.next/server/pages/api/auth/login.js:327:41)\n' +
notea-webapp |     '    at loop (/app/node_modules/next-connect/dist/index.cjs:69:47)\n' +
notea-webapp |     '    at next (/app/node_modules/next-connect/dist/index.cjs:74:13)\n' +
notea-webapp |     '    at Array.useCsrf (/app/.next/server/pages/index.js:2046:5)\n' +
notea-webapp |     '    at loop (/app/node_modules/next-connect/dist/index.cjs:69:47)\n' +
notea-webapp |     '    at next (/app/node_modules/next-connect/dist/index.cjs:74:13)\n' +
notea-webapp |     '    at /app/node_modules/next-iron-session/dist/index.js:137:7\n' +
notea-webapp |     '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
```

Cheers
