### ISSUE TITLE
Reverse proxy, security and sharing

### ISSUE THREAD

**Issue by robflate** [QingWei-Li/notea#67]
I wondered what the best method of securing Notea is while allowing public access to shared links. I have everything setup in Docker with Notea behind a [reverse proxy](https://hub.docker.com/_/traefik/) secured with [OAuth](https://hub.docker.com/r/thomseddon/traefik-forward-auth). In Notea I have the env var `DISABLE_PASSWORD=true` and allow public access to `/share` in my reverse proxy.

This successfully secures Notea whilst making shared notes publicly accessible but Notea also calls content from outside `/share` such as css and js. i.e. `/sw.js`, `/_next/`. Do I also need to allow public access to this content? I think I'm also running into some CORS issues.

Lastly, what is the recommended method for using images. At the moment, unless I set `DIRECT_RESPONSE_ATTACHMENT=true`, images upload to minio successfully but are greyed out in Notea and disappear when I refresh the page. I use `STORE_END_POINT=http://minio:9000` which docker resolves correctly to my minio container.

If anyone has any suggestions, I'd appreciate it. Thanks.

**Comment by espressoelf** [comment]
I've investigated a bit after having the same issue. Firefox wasn't really helping, but Chrome was.

> At the moment, unless I set `DIRECT_RESPONSE_ATTACHMENT=true`, images upload to minio successfully but are greyed out in Notea and disappear when I refresh the page. I use `STORE_END_POINT=http://minio:9000` which docker resolves correctly to my minio container.

This does make sense when reading the documentation of `DIRECT_RESPONSE_ATTACHMENT`:
> By default, requesting attachment links will redirect to S3 URL, Set to true to directly output attachments from the notea services. 

Which basically means that when set to `false`, the browser tries accessing `http://minio:9000` directly when _viewing_ images. Uploads are always proxied through the app, as you need the bucket's credentials. I'd suggest reverse-proxying MinIO, too, and put the external URL into your environment file. My configuration, for example:

### .env
```
STORE_ACCESS_KEY=noteaak
STORE_SECRET_KEY=noteask
STORE_BUCKET=notea
STORE_END_POINT=https://minio.domain.tld:443
# Required
STORE_FORCE_PATH_STYLE=true
PASSWORD=totallymypassword
```

### docker-compose.yml
```
version: '3.8'

services:
  app:
    image: cinwell/notea
#    ports:
#      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notea-rtr.tls=true"
      - "traefik.http.routers.notea-rtr.entrypoints=https"
      - "traefik.http.routers.notea-rtr.rule=Host(`notea.domain.tld`)"
    dns: "1.1.1.1"
    depends_on:
      - minio
    env_file: .env  
  minio:
    image: minio/minio
#    ports:
#      - '9000:9000'
#      - '9001:9001'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notea-minio-rtr.tls=true"
      - "traefik.http.routers.notea-minio-rtr.entrypoints=https"
      - "traefik.http.routers.notea-minio-rtr.rule=Host(`minio.domain.tld`)"
      - "traefik.http.routers.notea-minio-rtr.service=notea-minio-svc"
      - "traefik.http.services.notea-minio-svc.loadbalancer.server.port=9000"
      - "traefik.http.routers.notea-minio-console-rtr.tls=true"
      - "traefik.http.routers.notea-minio-console-rtr.entrypoints=https"
      - "traefik.http.routers.notea-minio-console-rtr.rule=Host(`minio-console.domain.tld`)"
      - "traefik.http.routers.notea-minio-console-rtr.service=notea-minio-console-svc"
      - "traefik.http.services.notea-minio-console-svc.loadbalancer.server.port=9001"
    volumes:
      - minio-data:/data
    environment:
      - "MINIO_ROOT_USER=admin"
      - "MINIO_ROOT_PASSWORD=totallymypassword"
    command: 'server /data --console-address ":9001"'

volumes:
  minio-data:
```
