### ISSUE TITLE
Unable to connect to Minio backend ECONNREFUSED 500

### ISSUE THREAD

**Issue by CMaclellan** [QingWei-Li/notea#75]
I'm trying to setup notea with a minio backend on a raspberry pi 4. I am able to get both containers running, but when I access notea via the browser I get errors after logging in saying "Failed to load tree". When I check the docker log I see that the connection to minio was unsuccessfull.

I confirmed that notea can ping minio so the two containers can talk.

**Error**
```
{
  name: 'Error',
  message: 'connect ECONNREFUSED 172.18.0.8:9001',
  status: 500,
  stack: 'Error: connect ECONNREFUSED 172.18.0.8:9001\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16)'
}
```

**Docker Compose**
```
version: '3.7'
services:
  notea:
    container_name: notea
    image: cinwell/notea:latest
    platform: linux/arm64
    init: true
    ports:
      - '3000:3000'
    environment:
      - PASSWORD=My Password
      - STORE_ACCESS_KEY=My Access Key
      - STORE_SECRET_KEY=My Secret Key
      - STORE_BUCKET=notea
      - STORE_END_POINT=http://minio:9001
      - STORE_FORCE_PATH_STYLE=true
      - BASE_URL=192.168.2.52
      - COOKIE_SECURE=false
    volumes:
      - /media/docker/config/notea:/data
```
